### ISSUE TITLE
Miner history table not presenting epochs after 314

### ISSUE THREAD

**Issue by hemulin** [agouin/0l-explorer#4]
![image](https://user-images.githubusercontent.com/1885510/190866115-f6149098-ec47-4c66-85cc-e41d8729431a.png)

Since few days, the table showing the proofs/epoch history is not presenting epochs beyond 314.

I tried digging in the codebase but failed to launch the project as all calls from the docker to various nodes returned with `ECONNREFUSED` :shrug:

**Comment by agouin** [comment]
closing stale issue
